### ISSUE TITLE
Error de StackOverflow con Tests de Duales en Tarea 4

### ISSUE THREAD

**Issue by artcidp** [lbenet/2016-2_TSFisicaComputacional#107]
En la última parte de la tarea 4, donde tenemos que hacer _tests_ para los métodos que definimos con duales quiero hacer un _test_ para el caso en el que una de las entradas del dual sea un _string_ o _char_ en vez de números reales. Al implementarlo me da un error de StackOverflow. Según tengo entendido, esto se debe al método de promotion que implementamos, por que promueve el real y el _string_ a tipo any y no puede operar con ellos. Sin embargo, ¿no debería primero marcar un error en el argumento si especifiqué que las entradas siempre deberían ser reales o subtipos de estos?

**Comment by lbenet** [comment]
Puedes mandar la liga a tus archivos concretos? Eso puede hacer más sencillo el reproducir el error...

**Comment by lbenet** [comment]
¿Quedó esto ya resuelto?

**Comment by artcidp** [comment]
Perdón, parece que aún persiste el mismo error. En la semana subimos los archivos de las tareas 4 y 5 que faltaban, incluyendo los módulos donde se hacen las definiciones pertinentes:

https://github.com/lbenet/2016-2_TSFisicaComputacional/blob/master/tareas/yvestruz/AutomDiff.jl
https://github.com/lbenet/2016-2_TSFisicaComputacional/blob/master/tareas/yvestruz/AutomDiff_T5.jl

El módulo de la tarea5 sólo es una extensión del de la tarea4 que, además de incluir las definiciones de los Duales y operaciones básicas, contiene métodos para las funciones trigonométricas, hiperbólica, etc. sobre duales. 

En realidad la duda no era el por qué daba este error sino si dicho error era el que debería dar. Por lo demás no hubo problemas con las tareas 4 y 5 y ya se realizó el _merge_.
