### ISSUE TITLE
Sobre relaciones de recurrencia en potencias

### ISSUE THREAD

**Issue by danmarurr** [lbenet/2016-2_TSFisicaComputacional#130]
Hola: 

Fernanda (@FernandaPerez) y yo nos dimos cuenta de que la relación de recurrencia para la potencia no puede calcular $P_{[0]}$, sin embargo sabemos que si el argumento de $P_a$ es un polinomio $g(x)$ con término independiente entonces $P_{a_{[0]}} = g_{[0]}^a$ y los cálculos funcionan.

Pero si $g(x)$ no tiene término independiente entonces la relación no funciona ¿Qué deberíamos considerar? ¿No hay problema con ello?
Nuestro avance está [aquí](https://github.com/danmarurr/2016-2_TSFisicaComputacional/blob/Clase29Marzo/tareas/danmarurr/09-DerivadasSuperiores.ipynb)

**Comment by UriAceves** [comment]
Suponiendo que tenemos $ g(x) = \sum_{k=0}^\infty g_k (x - x_0)^k $ y $a$ una constante, lo que deberían obtener es esto

![potencia](https://cloud.githubusercontent.com/assets/7073721/14321783/3b213136-fbe0-11e5-81b3-591aeefdec4b.png)

Si $g_0$ fuese cero nos estaríamos enfrentando a un problema que ya tuvimos antes. ¿Cuál? 

No encuentro sus cuentas para revisarlas o ver qué están haciendo. Su código no está comentado y tiene nombres que no son explícitos, lo cuál lo hace difícil de entender.

**Comment by lbenet** [comment]
Complementando lo que dijo @UriAceves, si empiezan por escribir 

$$
P_a(x) = (g(x))^a = \sum_{i=1}^n (P_a)_{[i]} (x-x0)^i,
$$

cuando evalúo en $x=x_0$ obtenemos $P_a(x_0) = (g(x_0))^a = (P_a)_{[0]}$. O sea, el término de orden cero se obtiene simplemente al evaluar en el punto alrededor del cual se hace la expansión.

(Espero que esto esté claro, pese a la falta de latex...)

**Comment by danmarurr** [comment]
Bueno, aquí pongo las cuentas que hicimos (en el notebook no se ven):

![alt text](https://github.com/danmarurr/2016-2_TSFisicaComputacional/blob/Imagenes/tareas/danmarurr/Imags/1.png?raw=true)

![alt text](https://github.com/danmarurr/2016-2_TSFisicaComputacional/blob/Imagenes/tareas/danmarurr/Imags/2.png?raw=true)

![alt text](https://github.com/danmarurr/2016-2_TSFisicaComputacional/blob/Imagenes/tareas/danmarurr/Imags/3.png?raw=true)

Nuestro problema es que para cuando queremos calcular la potencia de un polinomio sin término independiente ya no da.

**Comment by lbenet** [comment]
Creo que el problema está en el principio, desde el momento en que proponen el polinomio para $P_a(x)$: el coeficiente ${P_a}_{[0]}$ no corresponde al término independiente de $x$. Yo sugeriría verificar los índices de los coeficientes.
